/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module mojo_top_0 (
    input clk,
    input rst_n,
    input cclk,
    output reg spi_miso,
    input spi_ss,
    input spi_mosi,
    input spi_sck,
    output reg [3:0] spi_channel,
    input avr_tx,
    output reg avr_rx,
    input avr_rx_busy,
    input [23:0] io_dip,
    output reg [7:0] ledx,
    output reg [7:0] ledy
  );
  
  
  
  reg rst;
  
  wire [8-1:0] M_ledM_ledx;
  wire [8-1:0] M_ledM_ledy;
  reg [1-1:0] M_ledM_clk;
  reg [1-1:0] M_ledM_rst;
  reg [1-1:0] M_ledM_digit;
  ledMatrix_1 ledM (
    .clk(M_ledM_clk),
    .rst(M_ledM_rst),
    .digit(M_ledM_digit),
    .ledx(M_ledM_ledx),
    .ledy(M_ledM_ledy)
  );
  
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_2 reset_cond (
    .clk(clk),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  
  always @* begin
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out;
    spi_miso = 1'bz;
    spi_channel = 4'bzzzz;
    avr_rx = 1'bz;
    M_ledM_clk = clk;
    M_ledM_rst = rst;
    M_ledM_digit = 1'h0;
    ledx = M_ledM_ledx;
    ledy = M_ledM_ledy;
  end
endmodule
